name: Build and Test (branches)

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
    branches:    
      - 'feature/*'
      - 'fix/*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10', '3.11', '3.12', '3.13', '3.14']
    steps:
    - uses: actions/checkout@v6
    - name: Install uv
      uses: astral-sh/setup-uv@v8.1.0
      with:
        enable-cache: true
    - name: Set up Python
      run: uv python install ${{ matrix.python-version }}
    - name: Install dependencies
      run: uv sync --all-extras --dev
    - name: Lint code
      run: |
        uv run ruff check .
        uv run ruff format --check .
    - name: Build and test
      run: |
        uv run pytest --junitxml=junit/test-results-${{ matrix.python-version }}.xml --cov=semversioner --cov-report=term-missing --cov-report=xml
    - name: Upload coverage results
      uses: actions/upload-artifact@v7
      with:
        name: coverage-results-${{ matrix.python-version }}
        path: coverage.xml
      if: ${{ always() }}
    - name: Upload pytest test results
      uses: actions/upload-artifact@v7
      with:
        name: pytest-results-${{ matrix.python-version }}
        path: junit/test-results-${{ matrix.python-version }}.xml
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}
